# -*- coding: utf-8 -*-
# ruff: noqa
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openpi/pistream/proto/descriptor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openpi.pistream.proto import encoding_pb2 as openpi_dot_pistream_dot_proto_dot_encoding__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n&openpi/pistream/proto/descriptor.proto\x12\x10monopi.pi_stream\x1a$openpi/pistream/proto/encoding.proto"G\n\x12PiStreamDescriptor\x12\x31\n\x06\x66ields\x18\x01 \x03(\x0b\x32!.monopi.pi_stream.FieldDescriptor"b\n\x0f\x46ieldDescriptor\x12\x14\n\x0cpublisher_id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12,\n\x08\x65ncoding\x18\x03 \x01(\x0b\x32\x1a.monopi.pi_stream.Encodingb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "openpi.pistream.proto.descriptor_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_PISTREAMDESCRIPTOR"]._serialized_start = 98
    _globals["_PISTREAMDESCRIPTOR"]._serialized_end = 169
    _globals["_FIELDDESCRIPTOR"]._serialized_start = 171
    _globals["_FIELDDESCRIPTOR"]._serialized_end = 269
# @@protoc_insertion_point(module_scope)
