from __future__ import annotations

import dataclasses
from pathlib import Path
import time

import tyro

from examples.yam_real import data_regression


@dataclasses.dataclass
class Args:
    raw_dir: Path = Path("yam_data/raw")
    output: Path = Path("yam_data/manifests/pi05_yam_bimanual_50hz_20demo.txt")
    min_frames: int = 1


def main(args: Args) -> None:
    if not args.raw_dir.exists():
        raise FileNotFoundError(args.raw_dir)

    selected: list[tuple[str, int]] = []
    skipped: list[tuple[str, int]] = []
    for episode_dir in data_regression.discover_episodes(args.raw_dir, source_format="mcap"):
        episode = data_regression.load_mcap_episode(episode_dir)
        num_frames = episode.num_frames
        target = selected if num_frames >= args.min_frames else skipped
        target.append((episode_dir.name, num_frames))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# Generated by examples.yam_real.build_episode_manifest at {time.strftime('%Y-%m-%d %H:%M:%S')}",
        f"# raw_dir: {args.raw_dir}",
        f"# min_frames: {args.min_frames}",
        f"# selected_episodes: {len(selected)}",
        f"# selected_frames: {sum(num_frames for _, num_frames in selected)}",
        "",
    ]
    lines.extend(name for name, _ in selected)
    args.output.write_text("\n".join(lines) + "\n")

    print(f"Wrote {len(selected)} episodes to {args.output}")
    print(f"Selected frames: {sum(num_frames for _, num_frames in selected)}")
    if skipped:
        print("Skipped episodes:")
        for name, num_frames in skipped:
            print(f"  {name}: {num_frames} frames")


if __name__ == "__main__":
    main(tyro.cli(Args))
